# Generated by Django 5.0.1 on 2024-01-13 23:17

import django.urls.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.urls.base.reverse)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
